### ISSUE TITLE
bug: AttributeError: module 'semver' has no attribute 'Version'

### ISSUE THREAD

**Issue by dtrckd** [pawamoy/git-changelog#86]
I got his error on first use : 

```
> git-changelog --help
Traceback (most recent call last):
  File "/home/dtrckd/.local/bin/git-changelog", line 5, in <module>
    from git_changelog.cli import main
  File "/home/dtrckd/.local/lib/python3.9/site-packages/git_changelog/__init__.py", line 8, in <module>
    from git_changelog.build import Bitbucket, Changelog, Commit, GitHub, GitLab
  File "/home/dtrckd/.local/lib/python3.9/site-packages/git_changelog/build.py", line 21, in <module>
    from git_changelog.versioning import ParsedVersion, bump_pep440, bump_semver, parse_pep440, parse_semver
  File "/home/dtrckd/.local/lib/python3.9/site-packages/git_changelog/versioning.py", line 70, in <module>
    class SemVerVersion(semver.Version, ParsedVersion):  # type: ignore[misc]
AttributeError: module 'semver' has no attribute 'Version'
```

Version: 2.5.2
Python Version : 3.9.2
System : Debian/Linux

**Comment by pawamoy** [comment]
What version of semver do you have?

**Comment by pawamoy** [comment]
Can't reproduce, seems like you have an outdated version of `semver`, please try to upgrade it :slightly_smiling_face:
